[project]
name = "finance"
version = "0.1.0"
description = "个人财富管理应用"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "curl-cffi>=0.11.3",
    "numerize>=0.12",
    "plotly>=6.1.2",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.45.1",
    "yfinance>=0.2.61",
]
